from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index.html', views.index, name='index'),
    path('about.html', views.about, name='about'),
    path('archive.html', views.archive, name='archive'),
    path('author.html', views.author, name='author'),
    path('blog-list.html', views.blog_list, name='blog_list'),
    path('contact.html', views.contact, name='contact'),
    path('home-creative-blog.html', views.home_creative_blog, name='home_creative_blog'),
    path('home-creative-blog-dark.html', views.home_creative_blog_dark, name='home_creative_blog_dark'),
    path('home-default-dark.html', views.home_default_dark, name='home_default_dark'),
    path('home-lifestyle-blog.html', views.home_lifestyle_blog, name='home_lifestyle_blog'),
    path('home-lifestyle-blog-dark.html', views.home_lifestyle_blog_dark, name='home_lifestyle_blog_dark'),
    path('home-seo.html', views.home_seo, name='home_seo'),
    path('home-seo-blog.html', views.home_seo_blog, name='home_seo_blog'),
    path('home-seo-blog-dark.html', views.home_seo_blog_dark, name='home_seo_blog_dark'),
    path('home-tech-blog.html', views.home_tech_blog, name='home_tech_blog'),
    path('home-tech-blog-dark.html', views.home_tech_blog_dark, name='home_tech_blog_dark'),
    path('index-dark.html', views.index_dark, name='index_dark'),
    path('maintenance.html', views.maintenance, name='maintenance'),
    path('post-details.html', views.post_details, name='post_details'),
    path('post-format-gallery.html', views.post_format_gallery, name='post_format_gallery'),
    path('post-format-standard.html', views.post_format_standard, name='post_format_standard'),
    path('post-format-text.html', views.post_format_text, name='post_format_text'),
    path('post-format-video.html', views.post_format_video, name='post_format_video'),
    path('post-layout-1.html', views.post_layout_1, name='post_layout_1'),
    path('post-layout-2.html', views.post_layout_2, name='post_layout_2'),
    path('post-layout-3.html', views.post_layout_3, name='post_layout_3'),
    path('post-layout-4.html', views.post_layout_4, name='post_layout_4'),
    path('post-layout-5.html', views.post_layout_5, name='post_layout_5'),
    path('post-list.html', views.post_list, name='post_list'),
    path('practice.html', views.practice, name='practice'),
    path('privacy-policy.html', views.privacy_policy, name='privacy_policy'),
    path('typography.html', views.typography, name='typography'),
]
